spring:
  application:
    name: oneorder-clearing-system
    
  # 数据库配置（Docker环境）
  datasource:
    url: jdbc:postgresql://postgres:5432/oneorder_clearing
    username: oneorder
    password: oneorder123
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 30000
      
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
  # Redis配置（Docker环境）
  redis:
    host: redis
    port: 6379
    timeout: 6000ms
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
        
  # RabbitMQ配置（Docker环境）
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    
# 日志配置
logging:
  level:
    com.oneorder: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"