server:
  port: 8081

spring:
  application:
    name: oneorder-clearing-system
    
  # 数据库配置（本地测试）
  datasource:
    url: jdbc:postgresql://localhost:5433/oneorder_clearing
    username: oneorder
    password: oneorder123
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 30000
      
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
  # Redis配置（本地测试）
  redis:
    host: localhost
    port: 6380
    timeout: 6000ms
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
        
  # RabbitMQ配置（本地测试）
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
# 日志配置
logging:
  level:
    com.oneorder: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 清分系统配置
clearing:
  default-mode: star
  profit-sharing:
    default-rate: 0.5
  transit-entity:
    default-retention-rate: 0.03
  cross-border:
    enable-netting: true
    netting-threshold: 10000